services:
  frontend:
    build: 
      context: ./App
    volumes:
     - ./App
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./Database:/app/Database
    environment:
      - DB_PATH=/app/Database
      - IDENTITY_DB_PATH=/app/Database/Identity.db
      - BUSINESS_DB_PATH=/app/Database/Business.db
      - IDENTITY_MIGRATIONS_PATH=/app/Database/migrations/identity
      - BUSINESS_MIGRATIONS_PATH=/app/Database/migrations/business

volumes:
  database: